name: Purge cache

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Cloudflare Purge Cache Action
        uses: jakejarvis/cloudflare-purge-action@master
        env:
          CLOUDFLARE_ZONE: ${{secrets.CLOUDFLARE_ZONE_ID}}
          CLOUDFLARE_TOKEN: ${{secrets.CLOUDFLARE_API_KEY}}