name: Purge cache

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Cloudflare Purge Cache Action
        uses: 3stacks/cloudflare-purge-cache-action@v1.0.6
        with:
          authToken: ${{ secrets.CLOUDFLARE_API_KEY }}
          siteName: t4ccer.com
          authEmail: t4ccer@gmail.com
